// Pre-installed Blockchains Configuration
// 20+ EVM and 20+ Non-EVM blockchains

export interface BlockchainConfig {
  id: string;
  name: string;
  symbol: string;
  type: 'EVM' | 'SOLANA' | 'COSMOS' | 'NEAR' | 'APTOS' | 'SUI' | 'POLKADOT' | 'TON' | 'OTHER';
  chainId: number;
  rpcUrl: string;
  explorerUrl: string;
  explorerApiUrl: string;
  decimals: number;
  logoUrl: string;
  nativeToken: string;
  isActive: boolean;
}

// EVM Blockchains (20+)
export const evmBlockchains: BlockchainConfig[] = [
  { id: 'ethereum', name: 'Ethereum', symbol: 'ETH', type: 'EVM', chainId: 1, rpcUrl: 'https://eth.llamarpc.com', explorerUrl: 'https://etherscan.io', explorerApiUrl: 'https://api.etherscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png', nativeToken: 'ETH', isActive: true },
  { id: 'bsc', name: 'BNB Chain', symbol: 'BNB', type: 'EVM', chainId: 56, rpcUrl: 'https://bsc-dataseed.binance.org', explorerUrl: 'https://bscscan.com', explorerApiUrl: 'https://api.bscscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png', nativeToken: 'BNB', isActive: true },
  { id: 'polygon', name: 'Polygon', symbol: 'MATIC', type: 'EVM', chainId: 137, rpcUrl: 'https://polygon-rpc.com', explorerUrl: 'https://polygonscan.com', explorerApiUrl: 'https://api.polygonscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png', nativeToken: 'MATIC', isActive: true },
  { id: 'avalanche', name: 'Avalanche', symbol: 'AVAX', type: 'EVM', chainId: 43114, rpcUrl: 'https://api.avax.network/ext/bc/C/rpc', explorerUrl: 'https://snowtrace.io', explorerApiUrl: 'https://api.snowtrace.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/12559/small/Avalanche_Circle_RedWhite_Trans.png', nativeToken: 'AVAX', isActive: true },
  { id: 'arbitrum', name: 'Arbitrum One', symbol: 'ETH', type: 'EVM', chainId: 42161, rpcUrl: 'https://arb1.arbitrum.io/rpc', explorerUrl: 'https://arbiscan.io', explorerApiUrl: 'https://api.arbiscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/16547/small/photo_2023-03-29_21.47.00.jpeg', nativeToken: 'ETH', isActive: true },
  { id: 'optimism', name: 'Optimism', symbol: 'OP', type: 'EVM', chainId: 10, rpcUrl: 'https://mainnet.optimism.io', explorerUrl: 'https://optimistic.etherscan.io', explorerApiUrl: 'https://api-optimistic.etherscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/25244/small/Optimism.png', nativeToken: 'OP', isActive: true },
  { id: 'base', name: 'Base', symbol: 'ETH', type: 'EVM', chainId: 8453, rpcUrl: 'https://mainnet.base.org', explorerUrl: 'https://basescan.org', explorerApiUrl: 'https://api.basescan.org/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/31024/small/base.png', nativeToken: 'ETH', isActive: true },
  { id: 'fantom', name: 'Fantom', symbol: 'FTM', type: 'EVM', chainId: 250, rpcUrl: 'https://rpc.fantom.network', explorerUrl: 'https://ftmscan.com', explorerApiUrl: 'https://api.ftmscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/4001/small/Fantom_round.png', nativeToken: 'FTM', isActive: true },
  { id: 'cronos', name: 'Cronos', symbol: 'CRO', type: 'EVM', chainId: 25, rpcUrl: 'https://evm.cronos.org', explorerUrl: 'https://cronoscan.com', explorerApiUrl: 'https://api.cronoscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/7310/small/cro_token_logo.png', nativeToken: 'CRO', isActive: true },
  { id: 'gnosis', name: 'Gnosis Chain', symbol: 'GNO', type: 'EVM', chainId: 100, rpcUrl: 'https://rpc.gnosischain.com', explorerUrl: 'https://gnosisscan.io', explorerApiUrl: 'https://api.gnosisscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/662/small/logo_logomark_small.png', nativeToken: 'GNO', isActive: true },
  { id: 'klaytn', name: 'Klaytn', symbol: 'KLAY', type: 'EVM', chainId: 8217, rpcUrl: 'https://public-rpc.klaytn.net', explorerUrl: 'https://klaytnscope.com', explorerApiUrl: 'https://api.klaytnscope.com/api/v2', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/9672/small/klaytn.png', nativeToken: 'KLAY', isActive: true },
  { id: 'celo', name: 'Celo', symbol: 'CELO', type: 'EVM', chainId: 42220, rpcUrl: 'https://forno.celo.org', explorerUrl: 'https://explorer.celo.org', explorerApiUrl: 'https://explorer.celo.org/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/5568/small/celo.png', nativeToken: 'CELO', isActive: true },
  { id: 'harmony', name: 'Harmony', symbol: 'ONE', type: 'EVM', chainId: 1666600000, rpcUrl: 'https://api.harmony.one', explorerUrl: 'https://explorer.harmony.one', explorerApiUrl: 'https://explorer.harmony.one/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/4344/small/harmony_logo_di.png', nativeToken: 'ONE', isActive: true },
  { id: 'moonbeam', name: 'Moonbeam', symbol: 'GLMR', type: 'EVM', chainId: 1284, rpcUrl: 'https://rpc.api.moonbeam.network', explorerUrl: 'https://moonscan.io', explorerApiUrl: 'https://api.moonscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/22409/small/moonbeam.png', nativeToken: 'GLMR', isActive: true },
  { id: 'moonriver', name: 'Moonriver', symbol: 'MOVR', type: 'EVM', chainId: 1285, rpcUrl: 'https://rpc.moonriver.moonbeam.network', explorerUrl: 'https://moonriver.moonscan.io', explorerApiUrl: 'https://api.moonscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/9775/small/moonriver.png', nativeToken: 'MOVR', isActive: true },
  { id: 'aurora', name: 'Aurora', symbol: 'ETH', type: 'EVM', chainId: 1313161554, rpcUrl: 'https://mainnet.aurora.dev', explorerUrl: 'https://explorer.aurora.dev', explorerApiUrl: 'https://explorer.aurora.dev/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/14982/small/aurora.png', nativeToken: 'ETH', isActive: true },
  { id: 'linea', name: 'Linea', symbol: 'ETH', type: 'EVM', chainId: 59144, rpcUrl: 'https://rpc.linea.build', explorerUrl: 'https://lineascan.build', explorerApiUrl: 'https://api.lineascan.build/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/31465/small/linea.png', nativeToken: 'ETH', isActive: true },
  { id: 'zksync', name: 'zkSync Era', symbol: 'ETH', type: 'EVM', chainId: 324, rpcUrl: 'https://mainnet.era.zksync.io', explorerUrl: 'https://explorer.zksync.io', explorerApiUrl: 'https://api.zksync.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/31900/small/sync.png', nativeToken: 'ETH', isActive: true },
  { id: 'polygon_zkevm', name: 'Polygon zkEVM', symbol: 'ETH', type: 'EVM', chainId: 1101, rpcUrl: 'https://zkevm-rpc.polygon.technology', explorerUrl: 'https://zkevm.polygonscan.com', explorerApiUrl: 'https://api-zkevm.polygonscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/31872/small/polygon-zkevm.png', nativeToken: 'ETH', isActive: true },
  { id: 'scroll', name: 'Scroll', symbol: 'ETH', type: 'EVM', chainId: 534352, rpcUrl: 'https://rpc.scroll.io', explorerUrl: 'https://scrollscan.com', explorerApiUrl: 'https://api.scrollscan.com/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/31856/small/scroll.png', nativeToken: 'ETH', isActive: true },
];

// Non-EVM Blockchains (20+)
export const nonEvmBlockchains: BlockchainConfig[] = [
  { id: 'solana', name: 'Solana', symbol: 'SOL', type: 'SOLANA', chainId: 0, rpcUrl: 'https://api.mainnet-beta.solana.com', explorerUrl: 'https://solscan.io', explorerApiUrl: 'https://api.solscan.io', decimals: 9, logoUrl: 'https://assets.coingecko.com/coins/images/4128/small/solana.png', nativeToken: 'SOL', isActive: true },
  { id: 'cosmos', name: 'Cosmos Hub', symbol: 'ATOM', type: 'COSMOS', chainId: 0, rpcUrl: 'https://cosmos-rpc.polkachu.com', explorerUrl: 'https://mintscan.io/cosmos', explorerApiUrl: 'https://api.cosmos.network', decimals: 6, logoUrl: 'https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png', nativeToken: 'ATOM', isActive: true },
  { id: 'osmosis', name: 'Osmosis', symbol: 'OSMO', type: 'COSMOS', chainId: 0, rpcUrl: 'https://rpc-osmosis.keplr.app', explorerUrl: 'https://mintscan.io/osmosis', explorerApiUrl: 'https://api.osmosis.zone', decimals: 6, logoUrl: 'https://assets.coingecko.com/coins/images/16799/small/osmosis.png', nativeToken: 'OSMO', isActive: true },
  { id: 'near', name: 'Near Protocol', symbol: 'NEAR', type: 'NEAR', chainId: 0, rpcUrl: 'https://rpc.mainnet.near.org', explorerUrl: 'https://explorer.near.org', explorerApiUrl: 'https://api.nearblocks.io', decimals: 24, logoUrl: 'https://assets.coingecko.com/coins/images/10365/small/near.jpg', nativeToken: 'NEAR', isActive: true },
  { id: 'aptos', name: 'Aptos', symbol: 'APT', type: 'APTOS', chainId: 0, rpcUrl: 'https://aptos-mainnet.petra.dev', explorerUrl: 'https://aptoscan.com', explorerApiUrl: 'https://api.aptoscan.com', decimals: 8, logoUrl: 'https://assets.coingecko.com/coins/images/26455/small/aptos_round.png', nativeToken: 'APT', isActive: true },
  { id: 'sui', name: 'Sui', symbol: 'SUI', type: 'SUI', chainId: 0, rpcUrl: 'https://rpc.mainnet.sui.io', explorerUrl: 'https://suiscan.xyz', explorerApiUrl: 'https://api.sui.net', decimals: 9, logoUrl: 'https://assets.coingecko.com/coins/images/26375/small/sui_asset.jpeg', nativeToken: 'SUI', isActive: true },
  { id: 'polkadot', name: 'Polkadot', symbol: 'DOT', type: 'POLKADOT', chainId: 0, rpcUrl: 'https://rpc.polkadot.io', explorerUrl: 'https://polkadot.subscan.io', explorerApiUrl: 'https://api.subscan.io', decimals: 10, logoUrl: 'https://assets.coingecko.com/coins/images/12171/small/polkadot.png', nativeToken: 'DOT', isActive: true },
  { id: 'ton', name: 'Toncoin', symbol: 'TON', type: 'TON', chainId: 0, rpcUrl: 'https://toncenter.com/api/v2', explorerUrl: 'https://tonscan.org', explorerApiUrl: 'https://api.tonscan.org', decimals: 9, logoUrl: 'https://assets.coingecko.com/coins/images/17980/small/ton_symbol.png', nativeToken: 'TON', isActive: true },
  { id: 'algorand', name: 'Algorand', symbol: 'ALGO', type: 'OTHER', chainId: 0, rpcUrl: 'https://mainnet-api.algonode.org', explorerUrl: 'https://algoexplorer.io', explorerApiUrl: 'https://api.algoexplorer.io', decimals: 6, logoUrl: 'https://assets.coingecko.com/coins/images/4380/small/download.png', nativeToken: 'ALGO', isActive: true },
  { id: 'hedera', name: 'Hedera', symbol: 'HBAR', type: 'OTHER', chainId: 0, rpcUrl: 'https://mainnet.mirrornode.hedera.com', explorerUrl: 'https://hashscan.io', explorerApiUrl: 'https://api.mirrornode.hedera.com/api/v1', decimals: 8, logoUrl: 'https://assets.coingecko.com/coins/images/3688/small/hbar.png', nativeToken: 'HBAR', isActive: true },
  { id: 'multiversx', name: 'MultiversX', symbol: 'EGLD', type: 'OTHER', chainId: 0, rpcUrl: 'https://api.multiversx.com', explorerUrl: 'https://explorer.multiversx.com', explorerApiUrl: 'https://api.multiversx.com/graphql', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/12335/small/MultiversX.png', nativeToken: 'EGLD', isActive: true },
  { id: 'tezos', name: 'Tezos', symbol: 'XTZ', type: 'OTHER', chainId: 0, rpcUrl: 'https://mainnet.api.tez.ie', explorerUrl: 'https://tzstats.com', explorerApiUrl: 'https://api.tzstats.com', decimals: 6, logoUrl: 'https://assets.coingecko.com/coins/images/976/small/Tezos-logo.png', nativeToken: 'XTZ', isActive: true },
  { id: 'flow', name: 'Flow', symbol: 'FLOW', type: 'OTHER', chainId: 0, rpcUrl: 'https://flow-access-mainnet.g.chainflow.io', explorerUrl: 'https://flowscan.org', explorerApiUrl: 'https://api.flowscan.org', decimals: 8, logoUrl: 'https://assets.coingecko.com/coins/images/13446/small/5f6298c0c7a8cda55fb1c30cd773b93d.png', nativeToken: 'FLOW', isActive: true },
  { id: 'vechain', name: 'VeChain', symbol: 'VET', type: 'OTHER', chainId: 0, rpcUrl: 'https://mainnet.vechain.org', explorerUrl: 'https://vechainstats.com', explorerApiUrl: 'https://api.vechainstats.com', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/1167/small/VET_VETTERN.jpg', nativeToken: 'VET', isActive: true },
  { id: 'iotex', name: 'IoTeX', symbol: 'IOTX', type: 'OTHER', chainId: 0, rpcUrl: 'https://rpc.iotex.io', explorerUrl: 'https://iotexscan.io', explorerApiUrl: 'https://api.iotexscan.io/api', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/2718/small/iotex.png', nativeToken: 'IOTX', isActive: true },
  { id: 'ronin', name: 'Ronin', symbol: 'RON', type: 'OTHER', chainId: 2020, rpcUrl: 'https://ronin-rpc.roninchain.com', explorerUrl: 'https://ronin-explorer.roninchain.com', explorerApiUrl: 'https://api.roninscan.io', decimals: 18, logoUrl: 'https://assets.coingecko.com/coins/images/20009/small/ronin.jpg', nativeToken: 'RON', isActive: true },
  { id: 'zilliqa', name: 'Zilliqa', symbol: 'ZIL', type: 'OTHER', chainId: 0, rpcUrl: 'https://api.zilliqa.com', explorerUrl: 'https://viewblock.io/zilliqa', explorerApiUrl: 'https://api.viewblock.io/zilliqa', decimals: 12, logoUrl: 'https://assets.coingecko.com/coins/images/4500/small/zilliqa-zil.png', nativeToken: 'ZIL', isActive: true },
  { id: 'kadena', name: 'Kadena', symbol: 'KDA', type: 'OTHER', chainId: 0, rpcUrl: 'https://api.chainweb.com', explorerUrl: 'https://explorer.kadena.io', explorerApiUrl: 'https://api.kadena.io', decimals: 12, logoUrl: 'https://assets.coingecko.com/coins/images/5647/small/pol.png', nativeToken: 'KDA', isActive: true },
  { id: 'casper', name: 'Casper', symbol: 'CSPR', type: 'OTHER', chainId: 0, rpcUrl: 'https://rpc.clarityhub.io/mainnet', explorerUrl: 'https://cspr.live', explorerApiUrl: 'https://api.cspr.live', decimals: 9, logoUrl: 'https://assets.coingecko.com/coins/images/15899/small/casper.jpg', nativeToken: 'CSPR', isActive: true },
  { id: 'alephzero', name: 'Aleph Zero', symbol: 'AZERO', type: 'OTHER', chainId: 0, rpcUrl: 'https://rpc.azero.dev', explorerUrl: 'https://azero.dev', explorerApiUrl: 'https://api.azero.dev', decimals: 12, logoUrl: 'https://assets.coingecko.com/coins/images/17233/small/Aleph_Zero_logotype_wBg.png', nativeToken: 'AZERO', isActive: true },
];

export const allBlockchains = [...evmBlockchains, ...nonEvmBlockchains];
export default allBlockchains;